### PR TITLE
Update devDependencies

### LINKED ISSUE #42: Update devDependencies
https://david-dm.org/dwyl/learn-tape?type=dev
image

Should only take a minute to create PR in GitHub UI

### PR DESCRIPTION
**Pull request by nelsonic**
+ [x] Update version of `jsdom` and `tap` to latest versions fixes #42

### CODE REVIEW

**Comment by nelsonic** [comment]
Works flawlessly on `localhost`:
image

**Comment by nelsonic** [comment]
@iteles had to migrate from `istanbul` to `nyc` because `istanbul` no longer supported. 🙄 
Thanks for reviewing. 👍

**Review by iteles — APPROVED** [review]
Thanks @nelsonic, I guess that means we should probably update https://github.com/dwyl/learn-istanbul too!

**Comment by nelsonic** [comment]
@iteles indeed. separate issue https://github.com/dwyl/learn-istanbul/issues/20

**Pull request merged**
